[package]
name = "discord-tier-list-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.204"
serde_json = "1.0.120"
serenity = "0.12.2"
serenity-commands = "0.4.3"
serenity_utils = "0.7.0"
tokio = "1.38.1"
