# https://docs.docker.com/go/compose-spec-reference/

secrets:
  discord_token:
    file: ./discord_token.txt

services:
  db:
    container_name: tier-list-db
    image: postgres:16.3-alpine3.20
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tier_list
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    container_name: discord-tier-list-bot
    #    platform: "linux/amd64"
    build:
      context: .
      target: final
    image: crcblio.azurecr.io/discord-tier-list-bot:latest
    ports:
      - 2018:2018
    environment:
      PGHOST: host.docker.internal 
      PGPORT: 5432
      PGDBNAME: tier_list
      PGUSER: postgres
      PGPASS: postgres 
    secrets:
      - discord_token
    links:
        - db
    volumes:
      - './:/src'
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
    driver: local
