# https://docs.docker.com/go/compose-spec-reference/
services:
  db:
    container_name: tier-list-db
    image: postgres:16.3-alpine3.20
    restart: always
    environment:
      - POSTGRES_USER= /run/secrets/pg_user
      - POSTGRES_PASSWORD= /run/secrets/pg_password
      - POSTGRES_DB=tier_list
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - pg_user
      - pg_password

  server:
    container_name: discord-tier-list-bot
    build:
      context: .
      target: final
    image: discord-tier-list-bot
    ports:
      - 2018:2018
    environment:
      PGHOST: host.docker.internal 
      PGPORT: 5432
      PGDBNAME: tier_list
      PGUSER: /run/secrets/pg_user
      PGPASS: /run/secrets/pg_password 
      DISCORD_TOKEN: /run/secrets/discord_token
    secrets:
      - pg_user
      - pg_password
      - discord_token
    links:
        - db
    volumes:
      - './:/src'
    depends_on:
      db:
        condition: service_healthy

secrets:
  pg_user: 
    file: ./pg_user.txt
  pg_password:
    file: ./pg_password.txt
  discord_token:
    file: ./discord_token.txt


volumes:
  db:
    driver: local
