services:
  bot:
      image: discord-tier-list-bot/bot
      volumes:
        - type: bind
          source: ./config.toml
          target: ./README.md

      depends_on: [database, tier-list-service]
      network_mode: "host"
  database:
    image: postgres:13
    ports: [5432:5432]
    environment:
      POSTGRES_USER: tier_list
      POSTGRES_PASSWORD: tier_list_password
  tier-list-service:
    image: gnomeddev/tier-list-service
    volumes:
      - type: bind
        source: ${APP_CREDS}
        target: /gcp.json
    environment:
      - IPV6_BLOCK
      - LOG_LEVEL=INFO
      - BIND_ADDR=0.0.0.0:20310
      - APP_CREDS=/gcp.json
    network_mode: "host"
    expose: [20310]
