[package]
name = "events"
version = "0.1.0"
edition = "2021"

[dependencies]
poise.workspace = true
tokio.workspace = true
reqwest.workspace = true
serenity.workspace = true

core = { path = "../core" }
tasks = { path = "../tasks" }
